### ISSUE TITLE
Use Proxies to make indexable ndarrays

### ISSUE THREAD

**Issue by rajsite** [scijs/ndarray#40]
It would be interesting to see if Proxies: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

Can be used to make performant ndarrays with an indexer syntax.

```javascript
var mat = ndarray(new Float64Array([1, 0, 0, 1]), [2,2])
console.log(mat[1][2]);
```

It seems like the overhead might one proxy per dimension. Could be an interesting experiment! :)

**Comment by rreusser** [comment]
Neat idea! I think the main caveat would be speed. I know @kgryte has benchmarked this recently and found [proxies slow _all_ property access](https://twitter.com/kgryte/status/1024845094602469376) (I think all. correct me if I'm wrong. this is a major distinction) down by about a factor of 15x, which is a bit prohibitive. The numpy way is to vectorize everything and if single-element accessors are slow it's because you should've vectorized anyway. But then you get elaborate projects that compile python to c, all to get around slow interpreted loops. It seems like a bit of a shame to go down that path, though I agree it would be otherwise pretty outstanding.

You might be interested in @kgryte's work on [stdlib-js](https://github.com/stdlib-js/stdlib) since he's really working hard on exploring and analyzing all of these possibilities and really producing scientific-quality numerical software for js. Here's the [ndarray constructor docs](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/ndarray/ctor), for example.

**Comment by kgryte** [comment]
At this point, using `Proxy` is an absolute no-go. Wrapping an object in a `Proxy` automatically makes everything prohibitively slow, even if `Proxy` handlers are essentially no-ops. So, unfortunately, using `Proxy` is an interesting experiment, but likely to remain an experiment for the foreseeable future.

And, yes, for C-style multidimensional arrays, a `Proxy` handler must return a `Proxy`, which just compounds the problem. The more obvious approach would be to implement a slice syntax, but then you force string parsing for each element you access. In short, if performance is even remotely a concern, you will stick with the `.get()` method. If performance is not a concern (e.g., in a REPL environment), then using `Proxy` may be viable.

But what I can say is that in no shape or form will `Proxy` support be added to this package. If you want to do so, create a new package which wraps this one and hack a away.

**Comment by rreusser** [comment]
I don't want you to think the suggestion isn't very much appreciated, @rajsite, but for now I'll close this since @kgryte is correct that this repo simply isn't the correct place for a different ndarray front-end. Don't hesitate to follow up though! Glad to discuss further.

**Comment by kgryte** [comment]
@rajsite If you are interested in benchmarks, you can run them locally, provided you have setup and configured a development environment. The requisite file containing the benchmarks can be found [here](https://github.com/stdlib-js/stdlib/blob/80f46cdea21078a6f84343cb6994480de3ebb2bf/lib/node_modules/%40stdlib/proxy/ctor/benchmark/benchmark.js). Eventually, these benchmarks will be accessible through the stdlib project website, once we regenerate the docs, and you'll be able to run them in your browser. In the meantime, to get hard data, the project development environment is the best means. Should you pursue to run them, don't hesitate to ping us on the stdlib Gitter channel, if you have questions.
