### ISSUE TITLE
implementing ndarray in C++ for performance

### ISSUE THREAD

**Issue by AbhimanyuAryan** [scijs/ndarray#42]
Hi, numpy is implemented in C++ for performance whereas this is implemented in JavaScript itself. Do you think there will any performance hit for writing it in C++? 

Or we could have written it in C++ and then add v8 wrapper?

**Comment by rreusser** [comment]
For a start, see: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/ndarray

I believe they’ve done exactly what you’ve described and implemented it in C so that you can use whichever suits your environment for the best performance. Glad to follow up with further details but need to get to sleep! /cc @kgryte

**Comment by kgryte** [comment]
@rreusser Thanks for ping.

@AbhimanyuAryan Yes, you can get better runtime perf binding to a native implementation (provided data is sufficiently big; e.g., `1000` elements or more). We are currently (albeit too slowly) working on a C API for use in Node.js. There are, however, advantages to a pure JavaScript implementation compared to native bindings. Notably, portability and debugging. Hence, depending on the use case, you may want to choose one implementation over the other.

Feel free to ping us over at https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/ndarray, including on the stdlib Gitter channel, if you want to know more, etc.

Hope this helps!
